const filmes = [   
  { 
    id: '1',
    nome: 'Capitã marvel',
    imagem: '../imagens/heroi/capita_marvel.jpg',
    genero: 'héroi',
    link: '../links/capita_marvel.html',
    criado: '2019',
  },
  { 
    id: '2',
    nome: 'Lendas',
    imagem: './imagens/heroi/legends.jpg',
    genero: 'héroi',
    link: '../links/heroi/lendas.html',
    criado: '2021',
  },
  { 
    id: '3' ,
    nome: 'Pantera Negra',
    imagem: './imagens/heroi/pantera_negra.jpg',
    genero: 'héroi',
    link: '../links/heroi/pantera-negra.html',
    criado: '2018',
  },
  { 
    id: '4',
    nome: 'Thor',
    imagem: './imagens/heroi/thor.jpg',
    genero: 'héroi',
    link: '../links/heroi/thor.html',
    criado: '2011',
  },
  { 
    id: '5',
    nome: 'Venom',
    imagem: './imagens/heroi/venom.jpg',
    genero: 'héroi',
    link: '../links/heroi/venom.html',
    criado: '2018',
  },
  { 
    id: '1',
    nome: 'Amor sem medidas',
    imagem:'./imagens/comedia/amor_sem_medida.jpg',
    genero: 'Comédia',
    link: '../links/comedia/amor-sem-medidas.html',
    criado: '2021',
  },
  { 
    id: '2',
    nome: 'A princesa e plebeia',
    imagem:'./imagens/comedia/aprincesaeaplebeia.jpg',
    genero: 'Comédia',
    link: '../links/comedia/a-princesa-e-a-plebeia.html',
    criado: '2021',
  },
  { 
    id: '3',
    nome: 'Ghost Busters Mais Além',
    imagem:'./imagens/comedia/ghost.jpg',
    genero: 'Comédia',
    link: '../links/comedia/ghostbusters.html',
    criado: '2021',
  },
  { 
    id: '4',
    nome: 'Jornada da Vida',
    imagem:'./imagens/comedia/jornada_da_vida.jpg',
    genero: 'Comédia',
    link:'../links/comedia/jornada-da-vida.html',
    criado: '2019',
  },
  { 
    id: '5',
    nome: 'Lar doce inferno',
    imagem:'./imagens/comedia/lar_doce_inferno.jpg',
    genero: 'Comédia',
    link: '../links/comedia/lar-doce-inferno.html',
    criado: '2015',
  },
  { 
    id: '1',
    nome: '7 prisioneiros',
    imagem:'./imagens/crime/7prisioneiros.jpg',
    genero: 'Crime',
    link: '../links/acao/7-prisioneiros.html',
    criado: '2021',
  },
  { 
    id: '2',
    nome: 'Alerta Vermelho',
    imagem:'./imagens/crime/rednotice.jpg',
    genero: 'Crime',
    link: '../links/acao/alerta.html',
    criado: '2021',
  },
  { 
    id: '3',
    nome: 'Broadcast Signal Intrusion',
    imagem:'./imagens/crime/broadcast_signal_intrusion.jpg',
    genero: 'Crime',
    link: '../links/acao/broadcast.html',
    criado: '2021',
  },
  { 
    id: '4',
    nome: 'Entre tiros e beijos',
    imagem:'./imagens/crime/entre_tiros_e_beijos.jpg',
    genero: 'Crime',
    link: '../links/acao/entre-tiros-e-beijos.html',
    criado: '2021',
  },
  { 
    id: '5',
    nome: 'Livrai-nos do mal',
    imagem:'./imagens/crime/livrai-nosdomal.jpg',
    genero: 'Crime',
    link: '../links/acao/livrai-nos-do-mal.html',
    criado: '2014',
  },
  { 
    id: '1',
    nome: 'Guilty Party',
    imagem:'./imagens/series/guilty_party.jpg',
    genero: 'Série',
    link: '../links/serie/guilty-party.html',
    criado: '2021',
  },
  { 
    id: '2',
    nome: 'Hometown cha cha cha',
    imagem:'./imagens/series/hometown cha cha cha.jpg',
    genero: 'Série',
    link: '../links/serie/hometown.html',
    criado: '2021',
  },
  { 
    id: '3',
    nome: 'Refletidas',
    imagem:'./imagens/series/refletidas.jpg',
    genero: 'Série',
    link: '../links/serie/refletidas.html',
    criado: '2021',
  },
  { 
    id: '4',
    nome: 'Rio Shore',
    imagem:'./imagens/series/rio_shore.jpg',
    genero: 'Série',
    link: '../links/serie/rioshore.html',
    criado: '2021',
  },
  { 
    id: '5',
    nome: 'Un broken',
    imagem:'./imagens/series/un_broken.jpg',
    genero: 'Série',
    link: '../links/serie/unbroken.html',
    criado: '2021',
  },
];


export default filmes;
